version: '3.8'

services:
  # app:
  #   build: .
  #   volumes:
  #     - .:/app
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  db:
    image: postgres:14  
    environment:
      POSTGRES_DB: postgres      
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
