version: '3.2'  # Use a version appropriate for your Docker Compose features

services:
  scanner:
    image:  victorfaria/sitescan:3.4 # Use the same image as your Docker run command
    container_name: scanner
    depends_on: 
      - redis
    environment:  # Define environment variables from the command
      RL: 6
      RIPE_CONCURRENCY: 6
      WAPPALIZER_CONCURRENCY: 12
      HTTP_CONCURRENCY: 16
      NSLOOKUP_CONCURRENCY: 10
      DB_CONCURRENCY: 1
      MAX_SOCKETS: 50
      SANDBOXED: 'false'
      ONLYWAPPALYZERWORK: 'true'
      LINESTOLOAD: 1000000
    env_file:  # Include additional environment variables from a file
      - .env
    network_mode: host

    volumes:
      - ./domains.csv:/app/domains.csv  # Mounts domains.csv from the current directory to /app/domains.csv in the container
  
  redis:
    image: redis:6.2.12-alpine
    ports:
      - "6379:6379"
    network_mode: host

    volumes:
      - /redis-data:/data
    command: redis-server --save "" --appendonly no

  board:
    image: victorfaria/bullboard:1.0 
    container_name: board
    depends_on: 
      - scanner
    environment:  # Define environment variables from the command
      HOST: redis
    env_file:  # Include additional environment variables from a file
      - .env
    network_mode: host
