version: '3.2'

services:
 
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    network_mode: host
    env_file:  
      - .env
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PWD}

  board:
    image: victorfaria/bullboard:1.1
    ports:
      - "3000:3000"
    container_name: board
    depends_on: [redis]
    env_file:  # Include additional environment variables from a file
      - .env
    network_mode: host

volumes:
  postgres-data:
  redis-data:
