version: '3.8'  
services:
  scanner:
    image: victorfaria/sitescan:4.9  # Use the same image as your Docker run command
    container_name: scanner
    init: true
    depends_on:
      - redis
      - db
    # environment:  # Define environment variables from the command
    #   RL: 6
    #   RIPE_CONCURRENCY: 6
    #   WAPPALIZER_CONCURRENCY: 16
    #   HTTP_CONCURRENCY: 16
    #   NSLOOKUP_CONCURRENCY: 50
    #   DB_CONCURRENCY: 1
    #   MAX_SOCKETS: 50
    #   SANDBOXED: 'false'
    #   ONLYWAPPALYZERWORK: 'true'
    #   PG_HOST: 'localhost'
    #   PG_DATABASE: 'localhost'
    #   PG_USER: 'docker'
    #   PG_PASSWORD: 'docker'
    #   REDIS_HOST: 'localhost'
    env_file:  # Include additional environment variables from a file
      - .env
    network_mode: host

    volumes:
      - ./domains.csv:/app/domains.csv  # Mounts domains.csv from the current directory to /app/domains.csv in the container
      - /tmp:/tmp
    command: ["node","./dist/src/app.js", 'tagprocess']
      
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    network_mode: host

    volumes:
      - /redis-data:/data
    command: redis-server --save "" --appendonly no --requirepass ${REDIS_PWD}

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host


volumes:
  postgres-data:
