version: '3.8'  # Use a version appropriate for your Docker Compose features

services:
  scanner:
    image: victorfaria/sitescan  # Use the same image as your Docker run command
    container_name: scanner
    environment:  # Define environment variables from the command
      PT: "10"
      CPU: "2"
      RL: "3"
    env_file:  # Include additional environment variables from a file
      - .env
    networks:
      - default  # Uses the default network unless specified otherwise
    volumes:
      - ./domains.csv:/app/domains.csv  # Mounts domains.csv from the current directory to /app/domains.csv in the container

networks:
  default:
    driver: bridge
